=== silver137/517-Swartz-assignments/exercise-2/businesscard.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT businesscard (card)>
<!ELEMENT card (identity, role, contact, branding)>

<!-- Why not combine businesscard and card? -->

  <!ELEMENT identity (name, company)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT company (#PCDATA)>

  <!ELEMENT role (title)>
  <!ELEMENT title (#PCDATA)>

  <!ELEMENT contact (email, phone, website)>
  <!ELEMENT email (#PCDATA)>
  <!ELEMENT phone (#PCDATA)>
  <!ELEMENT website (#PCDATA)>

  <!ELEMENT branding (logo, colourscheme)>
  <!ELEMENT logo (#PCDATA)>

<!-- colourscheme is an element that needs definition -->
]>

=== silver137/517-Swartz-assignments/exercise-2/businesscard.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="businesscard.css"?>
<!DOCTYPE businesscard SYSTEM "businesscard.dtd">

<businesscard>
  <identity>
    <name>Denitsa Peneva</name>
    <company>UNC Chapel Hill</company>
  </identity>

  <role>
    <title>Research Intern - Literature Review Lead</title>
  </role>
  
  <contact>
    <email>name@unc.edu</email>
    <phone>123-456-7890</phone>
    <website>www.unc.edu</website>
  </contact>

  <branding>
    <logo>unc-logo.png</logo>
  </branding>

</businesscard>
